/* Meridiaan 2075 — werelden en opdrachten.
   sol is een korte schrijfwijze; de engine zet die om naar dezelfde boom als de leerling. */
(function (root) {
  function sc(id, a, b, body) {
    return '<svg viewBox="0 0 320 110" preserveAspectRatio="xMidYMid slice"><defs><linearGradient id="' + id + '" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="' + a + '"/><stop offset="1" stop-color="' + b + '"/></linearGradient></defs><rect width="320" height="110" fill="url(#' + id + ')"/>' + body + "</svg>";
  }
  const ART = [
    sc("a0", "#7dd3fc", "#e0e7ff", '<circle cx="262" cy="28" r="16" fill="#fde68a"/><g fill="#312e81"><rect x="18" y="52" width="30" height="58"/><rect x="56" y="30" width="26" height="80" fill="#4338ca"/><rect x="90" y="62" width="34" height="48"/><rect x="132" y="18" width="24" height="92" fill="#6366f1"/><rect x="164" y="48" width="38" height="62"/><rect x="212" y="36" width="28" height="74" fill="#4338ca"/></g><g fill="#fde68a"><rect x="62" y="42" width="5" height="5"/><rect x="72" y="58" width="5" height="5"/><rect x="138" y="34" width="5" height="5"/><rect x="176" y="62" width="5" height="5"/><rect x="220" y="52" width="5" height="5"/></g><ellipse cx="108" cy="30" rx="16" ry="4" fill="#2dd4bf"/><circle cx="108" cy="36" r="6" fill="#0b1220"/>'),
    sc("a1", "#bbf7d0", "#ecfdf5", '<g fill="#15803d"><rect x="24" y="40" width="22" height="70" rx="6"/><rect x="60" y="24" width="22" height="86" rx="6" fill="#16a34a"/><rect x="96" y="50" width="22" height="60" rx="6"/><rect x="132" y="30" width="22" height="80" rx="6" fill="#22c55e"/></g><path d="M190 110V56l40-30 40 30v54z" fill="#14532d"/><rect x="220" y="76" width="20" height="34" fill="#ecfccb"/><g fill="#38bdf8"><circle cx="40" cy="20" r="5"/><circle cx="110" cy="16" r="4"/><circle cx="150" cy="10" r="5"/></g>'),
    sc("a2", "#0f172a", "#312e81", '<g fill="#fff"><circle cx="30" cy="20" r="1.5"/><circle cx="90" cy="14" r="1"/><circle cx="150" cy="30" r="1.5"/><circle cx="300" cy="12" r="1.5"/><circle cx="220" cy="20" r="1"/></g><circle cx="250" cy="70" r="34" fill="#f59e0b"/><ellipse cx="250" cy="70" rx="52" ry="9" fill="none" stroke="#fde68a" stroke-width="3"/><rect x="60" y="62" width="70" height="20" rx="8" fill="#94a3b8"/><rect x="80" y="52" width="30" height="12" rx="4" fill="#38bdf8"/><circle cx="70" cy="72" r="3" fill="#2dd4bf"/><circle cx="90" cy="72" r="3" fill="#2dd4bf"/>'),
    sc("a3", "#0b1220", "#1e3a8a", '<g fill="#1e293b" stroke="#38bdf8"><rect x="30" y="24" width="50" height="86"/><rect x="100" y="14" width="50" height="96"/><rect x="170" y="30" width="50" height="80"/><rect x="240" y="20" width="50" height="90"/></g><g fill="#2dd4bf"><circle cx="42" cy="38" r="3"/><circle cx="42" cy="54" r="3"/><circle cx="112" cy="30" r="3"/><circle cx="182" cy="46" r="3"/><circle cx="252" cy="36" r="3"/></g><g fill="#f43f5e"><circle cx="42" cy="70" r="3"/><circle cx="112" cy="62" r="3"/><circle cx="252" cy="68" r="3"/></g>'),
    sc("a4", "#fdba74", "#7c2d12", '<circle cx="250" cy="26" r="12" fill="#fff7ed"/><path d="M0 110V70l50-30 50 34 60-40 70 44 90-34v66z" fill="#9a3412"/><path d="M0 110V88l70-20 80 22 90-18 80 20v18z" fill="#c2410c"/><path d="M120 110V84a26 26 0 0152 0v26z" fill="#e0f2fe"/><rect x="140" y="92" width="12" height="18" fill="#0ea5e9"/>'),
    sc("a5", "#0ea5e9", "#082f49", '<g fill="#bae6fd" opacity=".55"><circle cx="40" cy="30" r="5"/><circle cx="60" cy="50" r="3"/><circle cx="280" cy="24" r="6"/><circle cx="260" cy="60" r="3"/></g><path d="M0 110V90l60-10 80 14 90-12 90 10v18z" fill="#0c4a6e"/><g stroke="#22d3ee" stroke-width="4" fill="none"><path d="M40 110q-8-20 0-36"/><path d="M60 110q8-24 0-40"/></g><path d="M150 100V78a30 30 0 0160 0v22z" fill="#a5f3fc" opacity=".85"/><rect x="172" y="84" width="16" height="16" fill="#0369a1"/>')
  ];

  const base = (ops, logic, sensors) => ({ ops, logic: logic || [], sensors: sensors || [] });

  const WORLDS = [
    {
      id: "sky", suggest: 1, k: "Beginner", modus: "Visueel",
      n: "Skyline Meridiaan", art: ART[0],
      d: "Nova brengt energie naar de zwevende stad. Stuur haar naar het dock en haal verloren kernen op.",
      terms: { wall: "Nova vloog tegen een toren.", exit: "het dockingstation", core: "energiekernen", shield: "Een schild blokkeert de route. Schakel het eerst uit." },
      legend: { E: "dock", c: "energiekern" },
      levels: [
        { t: "Eerste vlucht", s: "Nova staat op het dak van Toren A. De wijk heeft stroom nodig.", goal: "Vlieg naar het dockingstation.", g: ["#####", "S...E", "#####"], sol: "F F F F", leer: "Opdrachten in de juiste volgorde zetten.", hints: ["Nova vliegt de kant op van haar neus.", "Tel de lege vakjes tot het dock.", "Vier keer vooruit."], nieuw: [{ id: "F", titel: "Vooruit", tekst: "Nova vliegt één vakje de kant op waar haar neus heen wijst." }], ...base(["F"]) },
        { t: "Om de hoek", s: "Zelfde dock, maar een toren staat in de rechte lijn. Vooruit alleen haalt het niet.", goal: "Bereik het dock met een bocht.", g: ["#####", "###E#", "###.#", "S...#", "#####"], sol: "F F F L F F", leer: "Een bekende route aanpassen als de baan een hoek krijgt.", hints: ["Eerst rechtdoor tot de muur.", "Draai links op de hoek.", "Daarna nog twee vooruit omhoog."], nieuw: [{ id: "L", titel: "Draai links", tekst: "Nova draait 90 graden linksom, zonder een vakje op te schuiven." }, { id: "R", titel: "Draai rechts", tekst: "Hetzelfde, maar rechtsom. Daarna wijst haar neus een andere kant op." }], ...base(["F", "L", "R"]) },
        { t: "Skybridge", s: "De brug is lang en recht. Acht keer hetzelfde opschrijven kan slimmer.", goal: "Bereik het dock.", hint: "Zelfde stap, heel vaak? Gebruik herhaal in Blokken of Code.", g: ["#########", "S.......E", "#########"], sol: "r8 { F }", leer: "Herhaling gebruiken in plaats van kopiëren.", hints: ["Tel de lege vakjes tot het dock.", "Dat is acht keer dezelfde stap.", "Gebruik herhaal 8 met vooruit erin."], nieuw: [{ id: "REP", titel: "Herhaal", tekst: "Zet stappen in een herhaal-blok. Nova voert ze het opgegeven aantal keer uit. In Visueel zie je de herhaling terug, bewerken doe je in Blokken of Code." }], ...base(["F", "L", "R"], ["rep"]) },
        { t: "Trappen", s: "Het dock ligt hoger. De trap lijkt op een herhaling, maar begint met één losse stap.", goal: "Klim naar het dock.", hint: "Eerst één vak vooruit. Daarna herhaalt hetzelfde stuk zich.", g: ["#####", "###.E", "##..#", "#..##", "S.###"], sol: "F r3 { L F R F }", leer: "Een patroon herkennen dat niet meteen bij de start begint.", hints: ["Eerst één vakje vooruit.", "Daarna herhaalt: links, vooruit, rechts, vooruit.", "Zet dat stuk in herhaal 3."], ...base(["F", "L", "R"], ["rep"]) },
        { t: "Energiekernen", s: "Langs de brug liggen twee kernen op gelijke afstand.", goal: "Pak beide kernen op en bereik het dock.", g: ["#######", "S.c.c.E", "#######"], sol: "r2 { F F C } F F", leer: "Een herhaald patroon van bewegen en pakken.", hints: ["Op een kern: pak op.", "Patroon: twee vooruit, pak.", "Herhaal dat twee keer, daarna naar het dock."], nieuw: [{ id: "C", titel: "Pak op", tekst: "Staat Nova op een energiekern, dan neemt ze die mee. Een leeg vakje levert niets op." }], ...base(["F", "L", "R", "C"], ["rep"]) },
        { t: "Zijcircuit", s: "Weer twee kernen, maar ze liggen niet op één lijn. Het oude patroon botst.", goal: "Verzamel beide kernen en dock.", g: ["#####", "S.c.#", "#...#", "#.c.E", "#####"], sol: "F F C R F F C L F F", leer: "Hetzelfde doel, een andere vorm: draaien tussen het pakken door.", hints: ["Eerst de bovenste kern.", "Draai naar de onderste kern.", "Pak op en vlieg naar het dock."], ...base(["F", "L", "R", "C"], ["rep"]) },
        { t: "Mast", s: "Een zendmast blokkeert het midden. Er liggen geen kernen.", goal: "Vlieg om de mast heen naar het dock.", g: ["######", "S....#", "#....#", "#...E#", "######"], sol: "F F F F R F F", leer: "Een route plannen voordat je hem uitvoert.", hints: ["De mast blokkeert niet de hele rij.", "Vlieg eerst langs de bovenkant.", "Rechtsaf naar het dock."], ...base(["F", "L", "R", "C"], ["rep"]) },
        { t: "Ongelijke kernen", s: "Drie kernen, maar de tussenruimte wisselt. Twee-vooruit-pak past niet overal.", goal: "Pak alle kernen op en bereik het dock.", g: ["##########", "S.c..c.c.E", "##########"], sol: "F F C F F F C F F C F F", leer: "Een patroon loslaten als de afstand verandert.", hints: ["De eerste kern zit dichtbij.", "Daarna zit er een extra leeg vak tussen.", "Tel elk stuk, of schrijf het uit."], ...base(["F", "L", "R", "C"], ["rep"]) },
        { t: "Kern opzij", s: "De kern ligt niet op de vliegbaan, maar één vak ernaast.", goal: "Pak de kern op en bereik het dock.", g: ["#######", "##c...#", "S.....#", "#....E#", "#######"], sol: "F F L F C R F F F R F F", leer: "Van de rechte lijn afwijken en daarna terugkeren.", hints: ["Vlieg tot onder de kern.", "Draai, pak, en ga weer recht.", "Aan het eind omlaag naar het dock."], ...base(["F", "L", "R", "C"], ["rep"]) },
        { t: "Onderdoor", s: "Het dock ligt onder de start, niet rechts. De mast dwingt een U-bocht.", goal: "Bereik het dock.", g: ["#######", "#S....#", "#.###.#", "#E....#", "#######"], sol: "F F F F R F F R F F F F", leer: "Een andere kant op eindigen dan waar je begon.", hints: ["Eerst helemaal naar rechts.", "Twee vakjes omlaag.", "Dan terug naar links, tot het dock."], ...base(["F", "L", "R", "C"], ["rep"]) },
        { t: "Kernen en bocht", s: "Eén kern boven, één kern onder. Een muur zit ertussen.", goal: "Pak beide kernen op en bereik het dock.", g: ["######", "S.c..#", "#..#.#", "#.cE.#", "######"], sol: "F F C F F R F F R F F C R R F", leer: "Pakken en draaien in één plan, zonder een vast ritme.", hints: ["Pak eerst de kern op de bovenste rij.", "Ga via rechts naar beneden.", "Pak de tweede kern en draai terug naar het dock."], ...base(["F", "L", "R", "C"], ["rep"]) },
        { t: "Stadsfinale", s: "Laatste vlucht: een kern boven, een opening, en een kern bij het dock.", goal: "Pak beide kernen op en bereik het dock.", g: ["#######", "S.c...#", "###.#.#", "#.c.E.#", "#######"], sol: "F F C F R F F R F C L L F F", leer: "Alles uit Skyline combineren in één route.", hints: ["Eerst de bovenste kern.", "Via de opening naar beneden.", "Pak de tweede kern en vlieg naar het dock."], ...base(["F", "L", "R", "C"], ["rep"]) }
      ]
    },
    {
      id: "hydro", suggest: 1, k: "Beginner", modus: "Visueel",
      n: "Hydrofarm", art: ART[1],
      d: "De verticale boerderij voedt de stad. Geef water, oogst en lever af bij het depot.",
      terms: { wall: "Nova vloog tegen een kaswand.", exit: "het depot", core: "energiekernen", plant: "De plant is droog. Geef eerst water.", plantEmpty: "Er staat geen dorstige plant voor Nova." },
      legend: { E: "depot", v: "dorstige plant", o: "oogst" },
      levels: [
        { t: "Eerste gietbeurt", s: "Een bed is droog. Nova kan er niet overheen tot de plant water heeft.", goal: "Geef water en bereik het depot.", g: ["#######", "S.v...E", "#######"], sol: "F W F F F F F", leer: "Een actie op het vakje vóór Nova, daarna pas verder vliegen.", hints: ["Water werkt op het vakje vóór Nova.", "Ga eerst één stap dichterbij.", "Geef water, daarna door naar het depot."], nieuw: [{ id: "W", titel: "Geef water", tekst: "Werkt op de dorstige plant direct voor Nova. Daarna is dat vakje vrij." }], ...base(["F", "L", "R", "W"]) },
        { t: "Om de leiding", s: "Weer één plant, maar de leiding dwingt een hoek. Rechtdoor lopen lukt niet.", goal: "Geef water en bereik het depot.", g: ["#####", "##.E#", "##v.#", "S..##", "#####"], sol: "F F L W F F R F", leer: "Dezelfde actie, een andere vorm van de kas.", hints: ["Klim eerst naar de plant.", "Draai en geef water.", "Verder naar het depot."], ...base(["F", "L", "R", "W"], ["rep"]) },
        { t: "Twee bedden", s: "Nu twee planten, op gelijke afstand. Het stuk herhaalt zich.", goal: "Geef beide planten water en bereik het depot.", hint: "Vooruit, water, vooruit — en dat herhalen.", g: ["#######", "S.v.v.E", "#######"], sol: "r2 { F W F } F F", leer: "Een lus om een reeks acties.", hints: ["Vooruit, water, vooruit.", "Dat stuk twee keer.", "Daarna nog naar het depot."], ...base(["F", "L", "R", "W"], ["rep"]) },
        { t: "Eerste oogst", s: "De vruchten zijn rijp. Nova moet ze meenemen, niet alleen voorbijvliegen.", goal: "Oogst beide vakken en bereik het depot.", g: ["#######", "S.o.o.E", "#######"], sol: "r2 { F F H } F F", leer: "Oogsten op het vakje waar Nova staat.", hints: ["Oogst op het vakje waar Nova staat.", "Twee vooruit en oogst, twee keer.", "Daarna naar het depot."], nieuw: [{ id: "H", titel: "Oogst", tekst: "Werkt als Nova op een rijpe plant staat. Daarna is de oogst binnen." }], ...base(["F", "L", "R", "W", "H"], ["rep"]) },
        { t: "Water en oogst", s: "Eerst het droge bed, daarna twee rijpe planten op een rij.", goal: "Geef water, oogst alles en bereik het depot.", g: ["#########", "S.v.o.o.E", "#########"], sol: "F W F F r2 { F H F } F", leer: "Twee soorten acties in één programma.", hints: ["Eerst water bij de droge plant.", "Daarna het oogstpatroon.", "Eindig bij het depot."], ...base(["F", "L", "R", "W", "H"], ["rep"]) },
        { t: "Kasbocht", s: "Zelfde werk: water en oogst. De oogst ligt nu boven de plant, niet ernaast.", goal: "Geef water, oogst en bereik het depot.", g: ["#####", "##oE#", "##..#", "S.v##", "#####"], sol: "F W F L F F H R F", leer: "Een rechte oplossing aanpassen aan een bocht.", hints: ["Water onderaan.", "Klim naar de oogst.", "Oogst en naar het depot."], ...base(["F", "L", "R", "W", "H"], ["rep"]) },
        { t: "Wisselende bedden", s: "Drie planten, maar niet op gelijke afstand. De lus van twee bedden faalt.", goal: "Geef alle planten water en bereik het depot.", g: ["##########", "S.v..v.v.E", "##########"], sol: "F W F F F W F F W F F F", leer: "Tellen als het patroon breekt.", hints: ["De eerste plant zit dichtbij.", "Daarna zit er een extra leeg vak tussen.", "De laatste twee planten staan weer tegen elkaar."], ...base(["F", "L", "R", "W", "H"], ["rep"]) },
        { t: "Dubbele oogst", s: "Oogst, plant, oogst. De volgorde is omgedraaid ten opzichte van water-dan-oogst.", goal: "Geef water, oogst beide vakken en bereik het depot.", g: ["#########", "S.o.v.o.E", "#########"], sol: "F F H F W F F F H F F", leer: "Acties afwisselen als de kas niet in één ritme staat.", hints: ["Eerst de eerste oogst.", "Geef daarna water voor je verder gaat.", "Oogst het tweede vak en door naar het depot."], ...base(["F", "L", "R", "W", "H"], ["rep"]) },
        { t: "Avondronde", s: "De plant staat op de klim, de oogst erboven, het depot ernaast.", goal: "Geef water, oogst en bereik het depot.", g: ["#######", "###oE##", "##.v.##", "S.....#", "#######"], sol: "F F F L W F F H R F", leer: "Klimmen, water geven en oogsten in één route.", hints: ["Klim naar de plant.", "Water, dan omhoog naar de oogst.", "Oogst en draai naar het depot."], ...base(["F", "L", "R", "W", "H"], ["rep"]) },
        { t: "Na de leiding", s: "Eerst water op de rechte rij. De oogst ligt pas na twee bochten.", goal: "Geef water, oogst en bereik het depot.", g: ["######", "S..v.#", "#....#", "##o.E#", "######"], sol: "F F W F F R F F R F F H R R F F", leer: "Een actie vroeg doen en de oogst later ophalen.", hints: ["Geef water op de bovenste rij.", "Ga rechtsom naar beneden.", "Oogst en draai terug naar het depot."], ...base(["F", "L", "R", "W", "H"], ["rep"]) },
        { t: "Oogst terug", s: "Na het water geven ligt de oogst boven je, en het depot achter je.", goal: "Geef water, oogst en bereik het depot.", g: ["#######", "#E.o..#", "#..v..#", "S.....#", "#######"], sol: "F F F L W F F H L F F", leer: "Terugdraaien als het doel niet voor je ligt.", hints: ["Loop tot onder de plant.", "Geef water en ga omhoog naar de oogst.", "Draai links naar het depot."], ...base(["F", "L", "R", "W", "H"], ["rep"]) },
        { t: "Twee rijen", s: "Eén plant op de eerste rij, de tweede pas na een bocht naar het depot.", goal: "Geef beide planten water en bereik het depot.", g: ["########", "S.v....#", "#....vE#", "########"], sol: "F W F F F F R W F L F", leer: "Twee keer water geven, met een draai ertussen.", hints: ["Eerste plant op de bovenste rij.", "Loop door tot boven de tweede plant.", "Draai, geef water, en het depot ligt ernaast."], ...base(["F", "L", "R", "W", "H"], ["rep"]) }
      ]
    },
    {
      id: "orbit", suggest: 2, k: "Gevorderd", modus: "Blokken",
      n: "Orbit-haven", art: ART[2],
      d: "Aan de ring hangen vrachtschepen achter energieschilden. Kijk vooruit en beslis.",
      terms: { wall: "Nova botste tegen de havenwand.", exit: "de sluis", core: "energiekernen", shield: "Een schild blokkeert de route. Schakel het eerst uit.", shieldEmpty: "Er staat geen schild voor Nova." },
      legend: { E: "sluis", x: "schild" },
      levels: [
        { t: "Eerste schild", s: "Een schild staat in de aanloopbaan. Nova kan er niet doorheen.", goal: "Schakel het schild uit en bereik de sluis.", g: ["#######", "S.x...E", "#######"], sol: "F X F F F F F", leer: "Een obstakel voor Nova uitschakelen vóór je verder vliegt.", hints: ["Schakel uit werkt vóór Nova.", "Eén stap dichterbij, dan uit.", "Door naar de sluis."], nieuw: [{ id: "X", titel: "Schakel uit", tekst: "Werkt op het schild direct voor Nova. Het vakje wordt daarna vrij." }], ...base(["F", "L", "R", "X"]) },
        { t: "Havenhoek", s: "Weer één schild, maar het zit in de bocht. Rechtdoor uit-en-door werkt niet.", goal: "Schakel het schild uit en bereik de sluis.", g: ["#####", "###E#", "##x.#", "S...#", "#####"], sol: "F F L X F R F L F", leer: "Dezelfde actie op een baan die afbuigt.", hints: ["Vlieg tot voor het schild.", "Schakel uit en draai verder.", "Naar de sluis."], ...base(["F", "L", "R", "X"], ["rep"]) },
        { t: "Twee schilden", s: "Twee schilden met dezelfde tussenruimte.", goal: "Schakel beide schilden uit en bereik de sluis.", g: ["#######", "S.x.x.E", "#######"], sol: "r2 { F X F } F F", leer: "Een herhaald patroon van vliegen en uitschakelen.", hints: ["Vooruit, uit, vooruit.", "Twee keer herhalen.", "Daarna naar de sluis."], ...base(["F", "L", "R", "X"], ["rep"]) },
        { t: "Kijk vooruit", s: "De schilden staan niet op een vaste tel-afstand. Tellen wordt onhandig.", goal: "Bereik de sluis zonder tegen een schild te vliegen.", hint: "In een herhaling: als er een schild staat, schakel het uit, anders vooruit.", g: ["#########", "S.x..x..E", "#########"], sol: "r10 { if schild { X } else { F } }", leer: "Een keuze (als / anders) binnen een lus.", hints: ["Tel niet — kijk.", "Als schild: uit. Anders: vooruit.", "Zet dat in een ruime herhaling."], nieuw: [{ id: "IF", titel: "Als", tekst: "Nova kijkt naar het vakje direct voor haar. Bij een schild doe je de stappen onder dan. Zo niet, dan de stappen onder anders." }], ...base(["F", "L", "R", "X"], ["rep", "if"], ["schild"]) },
        { t: "Baan met bocht", s: "Kijken vooruit haalt de schilden weg, maar aan het eind van de rij staat een muur.", goal: "Schakel de schilden uit en bereik de sluis.", hint: "Eerst de keuze-lus tot voor de muur. Daarna draaien.", g: ["#########", "S.x..x..#", "#######.#", "E.......#", "#########"], sol: "r9 { if schild { X } else { F } } R F F R F F F F F F F", leer: "Een keuze-lus is niet genoeg als de baan afbuigt.", hints: ["Gebruik als-schild tot je bijna bij de muur bent.", "Draai omlaag vóór je botst.", "Onder de ring terug naar de sluis."], ...base(["F", "L", "R", "X"], ["rep", "if"], ["schild"]) },
        { t: "Ringsegment", s: "De baan klapt omlaag en daarna terug. Onderweg staan twee schilden.", goal: "Schakel beide schilden uit en bereik de sluis.", g: ["#######", "S.x...#", "#####.#", "E.x...#", "#######"], sol: "F X F F F F R F F R F F X F F F", leer: "Bochten plannen en obstakels tussendoor oplossen.", hints: ["Eerst het bovenste schild.", "Volg de ring omlaag.", "Tweede schild, dan de sluis."], ...base(["F", "L", "R", "X"], ["rep", "if"], ["schild"]) },
        { t: "Schild onder", s: "De rechte baan is leeg. Het schild staat pas na de bocht.", goal: "Schakel het schild uit en bereik de sluis.", g: ["######", "S....#", "####.#", "Ex...#", "######"], sol: "F F F F R F F R F F X F F", leer: "Eerst de route, dan pas het schild — niet andersom.", hints: ["Boven is geen schild.", "Ga rechts de hoek om.", "Schakel uit als je het schild ziet, dan naar de sluis."], ...base(["F", "L", "R", "X"], ["rep", "if"], ["schild"]) },
        { t: "Dubbele ring", s: "Twee bochten en twee schilden, met ruimte ertussen.", goal: "Schakel beide schilden uit en bereik de sluis.", g: ["########", "S.x....#", "######.#", "E..x...#", "########"], sol: "F X F F F F F R F F R F F X F F F F", leer: "Een langere ring, niet dezelfde telling als het vorige segment.", hints: ["Eerst het bovenste schild.", "Volg de ring omlaag.", "Onderweg het tweede schild, dan de sluis."], ...base(["F", "L", "R", "X"], ["rep", "if"], ["schild"]) },
        { t: "Zigzag", s: "Twee schilden, elk op een andere rij. Een rechte lus botst op de muur.", goal: "Schakel beide schilden uit en bereik de sluis.", g: ["#####", "S.x.#", "#.x.#", "#..E#", "#####"], sol: "F X F F R F R X F F L F L F F", leer: "Per rij kijken en draaien, niet één keer vooruit blijven gaan.", hints: ["Eerste schild op de bovenste rij.", "Omlaag, dan het tweede schild.", "Daarna omlaag en naar de sluis."], ...base(["F", "L", "R", "X"], ["rep", "if"], ["schild"]) },
        { t: "Achter het schild", s: "De sluis ligt achter het schild, na een bocht naar links.", goal: "Schakel het schild uit en bereik de sluis.", g: ["######", "S....#", "####.#", "E.x..#", "######"], sol: "F F F F R F F R F X F F F", leer: "Het schild pas uitschakelen als je er echt voor staat.", hints: ["Eerst de lege rij uitvliegen.", "Twee keer rechtsaf.", "Schild uit, dan door naar de sluis."], ...base(["F", "L", "R", "X"], ["rep", "if"], ["schild"]) },
        { t: "Verspreide nadering", s: "De schilden staan anders gegroepeerd, en de sluis ligt om de hoek.", goal: "Bereik de sluis.", g: ["########", "S..x.x.#", "######.#", "E......#", "########"], sol: "r8 { if schild { X } else { F } } R F F R F F F F F F", leer: "Kijken én daarna nog een bocht plannen.", hints: ["Als schild uit, anders vooruit, tot voor de muur.", "Draai omlaag.", "Terug naar links tot de sluis."], ...base(["F", "L", "R", "X"], ["rep", "if"], ["schild"]) },
        { t: "Havenfinale", s: "Een schild boven, een schild onder, en de sluis aan de andere kant.", goal: "Schakel beide schilden uit en bereik de sluis.", g: ["#######", "S.x...#", "#####.#", "#E.x..#", "#######"], sol: "F X F F F F R F F R F X F F F", leer: "Ring, schilden en een laatste stuk terug naar de sluis.", hints: ["Bovenste schild eerst.", "Volg de opening naar beneden.", "Onderste schild uit, dan door naar de sluis."], ...base(["F", "L", "R", "X"], ["rep", "if"], ["schild"]) }
      ]
    },
    {
      id: "data", suggest: 2, k: "Gevorderd", modus: "Blokken",
      n: "Datacenter Kern", art: ART[3],
      d: "Servers vragen om de juiste kern. Rood bij rood, blauw bij blauw. Nova draagt er één tegelijk.",
      terms: { wall: "Nova botste tegen een serverrack.", exit: "de uitgang", core: "kernen" },
      legend: { E: "uitgang", r: "rode kern", b: "blauwe kern", R: "rood rack", B: "blauw rack" },
      levels: [
        { t: "Eén rode kern", s: "Een rode kern moet in het rode rack. Nova draagt maar één kern tegelijk.", goal: "Leg de kern in het rack en bereik de uitgang.", g: ["#######", "Sr.R..E", "#######"], sol: "F C F F Z F F F", leer: "Pakken, verplaatsen en op de juiste plek neerzetten.", hints: ["Pak op het vakje met de kern.", "Zet neer op het rode rack.", "Door naar de uitgang."], nieuw: [{ id: "Z", titel: "Zet neer", tekst: "Werkt als Nova op een rack staat en de kern dezelfde kleur heeft. Een verkeerde kleur past niet." }], ...base(["F", "L", "R", "C", "Z"]) },
        { t: "Verderop", s: "Weer één rode kern en één rack. Er zitten meer lege vakjes tussen.", goal: "Leg de kern in het rack en bereik de uitgang.", g: ["########", "S.r..R.E", "########"], sol: "F F C F F F Z F F", leer: "Hetzelfde werk, een andere afstand. Het korte programma is te vroeg.", hints: ["De kern ligt niet op het eerste vak.", "Tel tot het rack.", "Zet neer en loop door."], ...base(["F", "L", "R", "C", "Z"], ["rep"]) },
        { t: "Rood en blauw", s: "Twee kernen, twee racks, hetzelfde ritme.", goal: "Leg beide kernen goed en bereik de uitgang.", g: ["###########", "S.r.R.b.B.E", "###########"], sol: "r2 { F F C F F Z } F F", leer: "Een herhaald ritme van pakken en neerzetten.", hints: ["Ritme: twee vooruit, pak, twee vooruit, zet neer.", "Twee keer.", "Dan naar de uitgang."], ...base(["F", "L", "R", "C", "Z"], ["rep"]) },
        { t: "Kijk naar de kleur", s: "Twee rode paren, met een gat ertussen. Het ritme van rood-blauw past niet.", goal: "Leg beide kernen goed en bereik de uitgang.", hint: "Pak alleen als Nova echt op rood staat.", g: ["#############", "S.r.R...r.R.E", "#############"], sol: "F F if rood { C } F F Z F F F F if rood { C } F F Z F F", leer: "Een sensor gebruiken als een leeg vak anders een fout geeft.", hints: ["Eerste paar is dichtbij.", "Daarna vier lege vakjes.", "Pak alleen op rood, zet neer op het rack."], nieuw: [{ id: "IF", titel: "Als rood", tekst: "rood() is waar als Nova op een rode kern staat. Gebruik dat vóór pak, zodat een leeg vakje geen fout geeft." }], ...base(["F", "L", "R", "C", "Z"], ["rep", "if"], ["rood", "blauw"]) },
        { t: "Blauw verderop", s: "Rood zit dicht op zijn rack. Blauw heeft een extra vak nodig.", goal: "Leg beide kernen goed en bereik de uitgang.", g: ["############", "S.r.R.b..B.E", "############"], sol: "F F C F F Z F F C F F F Z F F", leer: "Per paar tellen, niet één lus over de hele gang.", hints: ["Rood eerst, kort ritme.", "Blauw heeft een extra leeg vak.", "Tel tot het blauwe rack."], ...base(["F", "L", "R", "C", "Z"], ["rep", "if"], ["rood", "blauw"]) },
        { t: "Grotere tussenruimte", s: "Twee rode paren. Na het eerste rack blijft de gang een stuk langer leeg dan net.", goal: "Leg beide kernen goed en bereik de uitgang.", g: ["###############", "S.r.R.....r.R.E", "###############"], sol: "F F C F F Z F F F F F F C F F Z F F", leer: "Een groter gat: het programma van de vorige rode opdracht is te kort.", hints: ["Eerste paar dichtbij.", "Daarna zes lege vakjes.", "Tweede paar weer twee vooruit, pak, twee vooruit, zet."], ...base(["F", "L", "R", "C", "Z"], ["rep", "if"], ["rood", "blauw"]) },
        { t: "Om het rack", s: "Het rode rack staat niet in de gang, maar om de hoek.", goal: "Leg de kern in het rack en bereik de uitgang.", g: ["######", "S.r..#", "####R#", "E....#", "######"], sol: "F F C F F R F Z F R F F F F", leer: "Dragen om de hoek naar het juiste rack.", hints: ["Pak de kern in de gang.", "Bocht naar het rack.", "Zet neer en terug naar de uitgang."], ...base(["F", "L", "R", "C", "Z"], ["rep", "if"], ["rood", "blauw"]) },
        { t: "Gebroken ritme", s: "Drie paren, te beginnen met blauw. Het middelste paar ligt verder weg.", goal: "Leg alle kernen goed en bereik de uitgang.", g: ["################", "S.b.B.r..R.b.B.E", "################"], sol: "F F C F F Z F F C F F F Z F F C F F Z F F", leer: "Een bekend ritme loslaten zodra één gat anders is.", hints: ["Eerste paar is blauw en kort.", "Het rode paar heeft een extra vak.", "Het laatste paar is weer kort."], ...base(["F", "L", "R", "C", "Z"], ["rep", "if"], ["rood", "blauw"]) },
        { t: "Blauwe bocht", s: "Een blauwe kern in de gang, het rack pas na twee bochten.", goal: "Leg de kern in het rack en bereik de uitgang.", g: ["######", "S.b..#", "####.#", "E..B.#", "######"], sol: "F F C F F R F F R F Z F F F", leer: "De hoek van het rode rack, nu met blauw en een langere terugweg.", hints: ["Pak de blauwe kern.", "Volg de rechterkant naar beneden.", "Zet neer op het blauwe rack en loop naar de uitgang."], ...base(["F", "L", "R", "C", "Z"], ["rep", "if"], ["rood", "blauw"]) },
        { t: "Serverhoek", s: "De kern moet mee de hoek om. Het rack staat niet in het verlengde.", goal: "Leg de kern in het rack en bereik de uitgang.", g: ["#######", "S.r...#", "#####R#", "E.....#", "#######"], sol: "F F C F F F R F Z F R F F F F F", leer: "Verder dragen dan één bocht lijkt.", hints: ["Pak de kern in de gang.", "Volg de bocht naar het rack.", "Zet neer en terug naar de uitgang."], ...base(["F", "L", "R", "C", "Z"], ["rep", "if"], ["rood", "blauw"]) },
        { t: "Wisselend paar", s: "Blauw heeft drie vakjes tot het rack, rood daarna twee.", goal: "Leg beide kernen goed en bereik de uitgang.", g: ["############", "S.b..B.r.R.E", "############"], sol: "F F C F F F Z F F C F F Z F F", leer: "Twee paren naast elkaar, elk met een eigen afstand.", hints: ["Blauw eerst: pak, drie vooruit, zet neer.", "Rood is korter.", "Eindig bij de uitgang."], ...base(["F", "L", "R", "C", "Z"], ["rep", "if"], ["rood", "blauw"]) },
        { t: "Datacenterfinale", s: "Drie paren. De gaten ertussen zijn niet gelijk.", goal: "Leg alle kernen goed en bereik de uitgang.", g: ["#################", "S.r.R..b.B.r..R.E", "#################"], sol: "F F C F F Z F F F C F F Z F F C F F F Z F F", leer: "Elk paar apart tellen in plaats van één lus.", hints: ["Rood, kort.", "Daarna een gat en blauw.", "Het laatste rode paar heeft weer een extra vak."], ...base(["F", "L", "R", "C", "Z"], ["rep", "if"], ["rood", "blauw"]) }
      ]
    },
    {
      id: "mars", suggest: 3, k: "Expert", modus: "Code",
      n: "Mars-kolonie", art: ART[4],
      d: "Kraters snijden de route naar de poort door. Bouw bruggen en schrijf zelf een functie.",
      terms: { wall: "Nova botste tegen een rots.", exit: "de koloniepoort", core: "voorraadkernen", crater: "Een krater blokkeert de route. Bouw eerst een brug.", craterEmpty: "Er ligt geen krater voor Nova." },
      legend: { E: "poort", k: "krater", c: "voorraadkern" },
      levels: [
        { t: "Eerste krater", s: "De vlakte is open, op één krater na. Zonder brug komt Nova niet verder.", goal: "Bouw een brug en bereik de poort.", g: ["#######", "S.k...E", "#######"], sol: "F G F F F F F", leer: "Een nieuw commando op het vakje vóór Nova.", hints: ["Brug op het vakje vóór Nova.", "Eén stap dichterbij.", "Bouw de brug en vlieg door naar de poort."], nieuw: [{ id: "G", titel: "Bouw brug", tekst: "Werkt op de krater direct voor Nova. Daarna kun je over het vakje vliegen." }], ...base(["F", "L", "R", "G"]) },
        { t: "Rand van de krater", s: "Weer één krater, maar hij ligt in de klim. Rechtdoor bouwen haalt de poort niet.", goal: "Bouw een brug en bereik de poort.", g: ["#####", "##.E#", "##k.#", "S..##", "#####"], sol: "F F L G F F R F", leer: "Dezelfde brug, een andere vorm van de vlakte.", hints: ["Klim tot voor de krater.", "Bouw de brug.", "Door naar de poort."], ...base(["F", "L", "R", "G"], ["rep"]) },
        { t: "Twee kraters", s: "Twee kraters, dezelfde tussenruimte.", goal: "Bouw beide bruggen en bereik de poort.", g: ["#######", "S.k.k.E", "#######"], sol: "r2 { F G F } F F", leer: "Een lus om een brug-patroon.", hints: ["Patroon: vooruit, brug, vooruit.", "Herhaal twee keer.", "Daarna twee vooruit."], ...base(["F", "L", "R", "G"], ["rep"]) },
        { t: "Voorraad", s: "Achter de eerste krater ligt een voorraadkern. Die moet mee.", goal: "Bouw de brug, pak de kern op en bereik de poort.", g: ["########", "S.k.c..E", "########"], sol: "F G F F F C F F F", leer: "Een brug en pakken in één rechte route.", hints: ["Eerst de brug.", "Dan de kern pakken.", "Door naar de poort."], ...base(["F", "L", "R", "G", "C"], ["rep"]) },
        { t: "Eigen functie", s: "Drie kraters, steeds hetzelfde stuk. Zet dat stuk in een functie.", goal: "Bereik de poort.", hint: "Schrijf een functie voor één krater en roep haar drie keer aan. Een lus mag ook.", g: ["#########", "S.k.k.k.E", "#########"], sol: "def over { F G F } r3 { call over } F F", leer: "Een herhaald stuk route een naam geven en aanroepen.", hints: ["Eén functie = één krater.", "Drie keer aanroepen, of een lus.", "Daarna twee vooruit naar de poort."], nieuw: [{ id: "DEF", titel: "Functie", tekst: "In Code schrijf je function over() { ... } en daarna over();. In Python: def over(): en daarna over(). De stappen in de functie gebeuren pas als je haar aanroept." }], ...base(["F", "L", "R", "G", "C"], ["rep", "def"]) },
        { t: "Bocht na de brug", s: "De functie voor een rechte krater is hier niet genoeg: de tweede krater ligt omhoog.", goal: "Bouw beide bruggen en bereik de poort.", g: ["#####", "##.E#", "##k.#", "S.k##", "#####"], sol: "def rechtdoor { F G F } call rechtdoor L G F F R F", leer: "Een functie dekt één vorm. Een bocht vraagt extra stappen.", hints: ["Eerste krater is recht: dat kan in een functie.", "Draai voor de tweede krater.", "Bouw de brug en vlieg naar de poort."], ...base(["F", "L", "R", "G", "C"], ["rep", "def"]) },
        { t: "Kern boven de rand", s: "Eerst de krater, dan de kern, dan de poort om de hoek.", goal: "Bouw de brug, pak de kern op en bereik de poort.", g: ["#####", "##cE#", "##k.#", "S..##", "#####"], sol: "F F L G F F C R F", leer: "Een korte route mag uitgeschreven, zonder functie.", hints: ["Klim naar de krater.", "Brug, dan de kern.", "Draai naar de poort."], ...base(["F", "L", "R", "G", "C"], ["rep", "def"]) },
        { t: "Konvooi", s: "Twee keer hetzelfde: krater, kern, en door.", goal: "Bouw de bruggen, pak beide kernen op en bereik de poort.", hint: "Een functie stap() kan precies één krater-plus-kern doen.", g: ["###########", "S.k.c.k.c.E", "###########"], sol: "def stap { F G F F F C } call stap call stap F F", leer: "Een functie ontwerpen die één volledig deelprobleem oplost.", hints: ["Functie: brug, doorlopen, kern pakken.", "Twee aanroepen.", "Dan naar de poort."], ...base(["F", "L", "R", "G", "C"], ["rep", "def"]) },
        { t: "Ongelijke kraters", s: "Drie kraters, niet op gelijke afstand. Drie keer dezelfde functie botst.", goal: "Bouw alle bruggen en bereik de poort.", g: ["##########", "S.k..k.k.E", "##########"], sol: "F G F F F G F F G F F F", leer: "Een functie of lus alleen gebruiken waar de afstand klopt.", hints: ["Eerste krater dichtbij.", "Daarna een extra leeg vak.", "De laatste twee kraters staan weer dichter op elkaar."], ...base(["F", "L", "R", "G", "C"], ["rep", "def"]) },
        { t: "Kern na de bocht", s: "De krater ligt rechtsboven, de kern eronder, de poort daaronder.", goal: "Bouw de brug, pak de kern op en bereik de poort.", g: ["######", "S..k.#", "#..c.#", "##.E.#", "######"], sol: "F F G F F R F R F C L F", leer: "Brug, kern en bocht in een volgorde die niet recht is.", hints: ["Loop tot voor de krater.", "Brug, dan omlaag naar de kern.", "Pak op en draai naar de poort."], ...base(["F", "L", "R", "G", "C"], ["rep", "def"]) },
        { t: "Tussenruimte", s: "Twee keer krater-plus-kern, maar er zit een leeg vak tussen de paren.", goal: "Bouw de bruggen, pak beide kernen op en bereik de poort.", g: ["############", "S.k.c..k.c.E", "############"], sol: "def stap { F G F F F C } call stap F call stap F F", leer: "Een functie hergebruiken en tussendoor één extra stap zetten.", hints: ["Maak een functie voor krater plus kern.", "Na de eerste aanroep één vak extra vooruit.", "Roep de functie nog eens aan, dan de poort."], ...base(["F", "L", "R", "G", "C"], ["rep", "def"]) },
        { t: "Kraterfinale", s: "Eerst een krater op de vlakte, daarna een kern om de hoek, dan de poort.", goal: "Bouw de brug, pak de kern op en bereik de poort.", g: ["#######", "S.k...#", "#....c#", "##E...#", "#######"], sol: "F G F F F F R F C F R F F F", leer: "De laatste route: brug, dragen en twee bochten.", hints: ["Brug op de bovenste rij.", "Rechtsom naar de kern.", "Pak op en naar links naar de poort."], ...base(["F", "L", "R", "G", "C"], ["rep", "def"]) }
      ]
    },
    {
      id: "deep", suggest: 3, k: "Expert", modus: "Code",
      n: "Diepzee-lab", art: ART[5],
      d: "Onder de stad zitten sluizen op slot met een schild. Nova haalt monsters op en vindt zelf de weg.",
      terms: { wall: "Nova botste tegen de labwand.", exit: "het laboratorium", core: "monsters", shield: "Een schild blokkeert de sluis. Schakel het eerst uit.", shieldEmpty: "Er staat geen schild voor Nova." },
      legend: { E: "lab", x: "sluis", c: "monster" },
      levels: [
        { t: "Sluis open", s: "De deur heeft een energieschild. Zonder uitschakelen blijft hij dicht.", goal: "Open de sluis en bereik het lab.", g: ["#######", "S.x...E", "#######"], sol: "F X F F F F F", leer: "Een bekend commando in een nieuwe omgeving.", hints: ["Schakel uit vóór Nova.", "Eén stap dichterbij.", "Door naar het lab."], ...base(["F", "L", "R", "X"]) },
        { t: "Eerste monster", s: "In de buis drijft een monster. Er is geen schild.", goal: "Pak het monster op en bereik het lab.", g: ["#######", "S.c...E", "#######"], sol: "F F C F F F F", leer: "Pakken op het vakje waar Nova staat.", hints: ["Twee vooruit, dan pakken.", "Het monster ligt op de baan.", "Daarna door naar het lab."], ...base(["F", "L", "R", "X", "C"]) },
        { t: "Monster opzij", s: "Weer één monster, maar het ligt niet op de rechte buis.", goal: "Pak het monster op en bereik het lab.", g: ["######", "S....#", "#.c..#", "#...E#", "######"], sol: "F F R F C F L F F", leer: "Hetzelfde doel, een zijbuis. Rechtdoor mist het monster.", hints: ["Twee vakjes vooruit.", "Omlaag naar het monster.", "Pak op en draai naar het lab."], ...base(["F", "L", "R", "X", "C"]) },
        { t: "Schild of door", s: "Twee sluizen, niet op gelijke afstand. Kijk vooruit.", goal: "Bereik het lab.", g: ["#########", "S.x..x..E", "#########"], sol: "r10 { if schild { X } else { F } }", leer: "Een keuze in code: if / else.", hints: ["Kijk vooruit.", "Als schild: uit. Anders: vooruit.", "Herhaal tot het lab."], ...base(["F", "L", "R", "X", "C"], ["rep", "if"], ["schild"]) },
        { t: "Tot het lab", s: "De buis is recht en leeg. Je hoeft de vakjes niet te tellen.", goal: "Bereik het lab.", hint: "while (!gedockt()) of while not gedockt(): blijf vooruitgaan tot Nova op het doel staat.", g: ["###########", "S.........E", "###########"], sol: "while { F }", leer: "Een lus die stopt op een voorwaarde, niet op een getal.", hints: ["Tel niet.", "Zolang Nova niet bij het lab is: vooruit.", "De lus stopt vanzelf op het doel."], nieuw: [{ id: "WHILE", titel: "Zolang", tekst: "gedockt() is waar als Nova op het doel staat. while (!gedockt()) { vooruit(); } blijft dus gaan tot ze daar is. In Python: while not gedockt():" }], ...base(["F", "L", "R", "X", "C"], ["rep", "if", "while"], ["schild"]) },
        { t: "De bocht", s: "Alleen vooruit lopen botst. De buis klapt naar beneden. Bij een muur: rechtsaf.", goal: "Open de sluis en bereik het lab.", hint: "Zolang niet gedockt: schild uit, anders bij een muur rechtsaf, anders vooruit.", g: ["######", "S....#", "####.#", "E.x..#", "######"], sol: "while { if schild { X } else { if muur { R } else { F } } }", leer: "De rechte while werkt niet meer: de buis heeft een hoek.", hints: ["Bij een schild: uit.", "Bij een muur: rechts.", "Anders vooruit, tot het lab."], ...base(["F", "L", "R", "X", "C"], ["rep", "if", "while"], ["schild", "muur"]) },
        { t: "Sluis en monster", s: "Sluizen en monsters wisselen op een rechte buis.", goal: "Open elke sluis, pak elk monster op en bereik het lab.", hint: "Zolang niet bij het lab: schild uit of vooruit, en pak op als Nova op een monster staat.", g: ["#############", "S.x.c.x.c.x.E", "#############"], sol: "while { if schild { X } else { F } if kern { C } }", leer: "Een voorwaarde-lus met een sensor op het huidige vakje.", hints: ["Zolang niet bij het lab.", "Schild? Uit. Anders vooruit.", "Op een monster? Pak op."], ...base(["F", "L", "R", "X", "C"], ["rep", "if", "while"], ["schild", "kern"]) },
        { t: "Lab bereikt", s: "De bocht van net, plus een monster in de bovenbuis. Rechtsaf-alleen mist de vondst niet, maar je moet wel pakken.", goal: "Pak het monster op, open de sluis en bereik het lab.", g: ["######", "Sc...#", "####.#", "E.x..#", "######"], sol: "while { if schild { X } else { if muur { R } else { F } } if kern { C } }", leer: "De bocht-lus uitbreiden met pakken.", hints: ["Zelfde keuzes als bij de bocht.", "Extra: op een monster pakken.", "Eén while voor de hele duik."], ...base(["F", "L", "R", "X", "C"], ["rep", "if", "while"], ["schild", "kern", "muur"]) },
        { t: "Linksaf", s: "De opening zit de andere kant op. Rechtsaf draaien loopt vast.", goal: "Open de sluis en bereik het lab.", hint: "Bij een muur nu linksaf, niet rechtsaf.", g: ["######", "#...E#", "####x#", "S....#", "######"], sol: "while { if schild { X } else { if muur { L } else { F } } }", leer: "De vorm lijkt op de bocht, de draairichting is anders.", hints: ["Loop de onderste buis uit.", "Bij een muur: links.", "Schild uit, dan ben je bij het lab."], ...base(["F", "L", "R", "X", "C"], ["rep", "if", "while"], ["schild", "muur"]) },
        { t: "Linksaf met monster", s: "Zelfde soort bocht naar links, nu met een monster vóór het lab.", goal: "Pak het monster op, open de sluis en bereik het lab.", g: ["######", "#E.c.#", "####x#", "S....#", "######"], sol: "while { if schild { X } else { if muur { L } else { F } } if kern { C } }", leer: "Linksaf én pakken. Het rechtsaf-programma komt hier niet aan.", hints: ["Muur betekent links.", "Schild uit op de klim.", "Pak het monster voor je het lab in gaat."], ...base(["F", "L", "R", "X", "C"], ["rep", "if", "while"], ["schild", "kern", "muur"]) },
        { t: "Andere volgorde", s: "Rechte buis, maar eerst monsters en pas daarna sluizen. Tellen faalt, kijken niet.", goal: "Open elke sluis, pak elk monster op en bereik het lab.", g: ["###########", "S.c.x.c.x.E", "###########"], sol: "while { if schild { X } else { F } if kern { C } }", leer: "De aanpak blijft, de volgorde op de kaart is anders.", hints: ["Niet tellen.", "Schild uit of vooruit.", "Pakken als Nova op een monster staat."], ...base(["F", "L", "R", "X", "C"], ["rep", "if", "while"], ["schild", "kern"]) },
        { t: "Diepzeefinale", s: "Langere bocht naar links, een schild en een monster onderweg.", goal: "Pak het monster op, open de sluis en bereik het lab.", g: ["#######", "#E.c..#", "#####x#", "S.....#", "#######"], sol: "while { if schild { X } else { if muur { L } else { F } } if kern { C } }", leer: "Linksaf, schild en monster in één programma.", hints: ["Zolang niet bij het lab.", "Muur: links. Schild: uit.", "Monster: pakken."], ...base(["F", "L", "R", "X", "C"], ["rep", "if", "while"], ["schild", "kern", "muur"]) }
      ]
    }
  ];

  const GUIDE = [
    { h: "Drie niveaus, één programma", p: "Visueel is tikken met iconen. Blokken is slepen en nesten. Code is JavaScript of Python." },
    { h: "Opbouw", p: "Zes werelden met opdrachten van beginner tot expert." },
    { h: "Docentknop", p: "Ontgrendelt werelden en toont leerdoelen." },
    { h: "Kerndoelen", p: "Digitale geletterdheid en computational thinking voor groep 7–8 en VO." }
  ];

  const api = { WORLDS, GUIDE, LESKAART: [] };
  if (root.ITCExtra && root.ITCExtra.apply) root.ITCExtra.apply(api);
  root.ITCCatalog = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
